plugin:
    mode: simple
    verbosity: all
    model:
        file: /usr/local/etc/snort/dns-firewall/basic.dfw3model
        weight: 1000000
    whitelist:  /usr/local/etc/snort/dns-firewall/whitelist.txt
    blacklist:  /usr/local/etc/snort/dns-firewall/blacklist.txt
    timeframe:
        enabled: true
        period: 600
        max-queries: 1000
        penalty: 0.01
    hmm:
        enabled: true
        min-length: 7
        bias: 0.1
        weight: 10
    entropy:
        enabled: true
        min-length: 7
        bias: 1.0
        weight: 10
    reject:
        block-period: 5
        threshold: 0

trainer:
    dataset:
        filename: data/rb-domains.log
        max-lines: -1
    model-file: bin/basic.dfw3model
    max-length:
        percentile: 0.99
        penalty: 0.1
    hmm:
        min-length: 5
        hidden-states: 8
        learning-rate: 0.0001
        batch-size: 4096
    entropy:
        min-length: 5
        bins: 1000
        scale: log
        window-widths: [
            100,300,1000,3000
        ]
