plugin:
    mode: simple
    verbosity: all
    model:
        file: /usr/local/etc/snort/dns-firewall/basic.dfw3model
        weight: 1000000
    whitelist:  /usr/local/etc/snort/dns-firewall/whitelist.txt
    blacklist:  /usr/local/etc/snort/dns-firewall/blacklist.txt
    timeframe:
        enabled: true
        period: 600
        max-queries: 600
    hmm:
        enabled: true
        min-length: 7
        weight: 10
    entropy:
        enabled: true
        min-length: 7
        weight: 10
    short-reject:
        block-period: 5
        threshold: -1
        repetitions: 1
    long-reject:
        block-period: 60
        threshold: -2
        repetitions: 5
    permanent-reject:
        threshold: -3
        repetitions: 10

trainer:
    dataset:
        filename: data/rb-domains.log
        max-lines: -1
    model-file: bin/basic.dfw3model
    max-length:
        percentile: 0.99
        penalty: 0.1
    hmm:
        min-length: 7
        hidden-states: 8
        learning-rate: 0.0001
        batch-size: 4096
    entropy:
        min-length: 7
        bins: 1000
        scale: log
        window-widths: [
            30,100,300,1000
        ]
