plugin:
    mode: simple
    verbosity: all
    model:
        file: /etc/snort/dns-firewall/basic.dfw3model
        weight: 1000000
    whitelist:  /etc/snort/dns-firewall/whitelist.txt
    blacklist:  /etc/snort/dns-firewall/blacklist.txt
    timeframe:
        period: 600
        max-queries: 600
    hmm:
        min-length: 8
        weight: 10
    entropy:
        min-length: 0
        weight: 10
    short-reject:
        block-period: 5
        threshold: -2
        repetitions: 1
    long-reject:
        block-period: 60
        threshold: -3
        repetitions: 5
    permanent-reject:
        threshold: -4
        repetitions: 10

trainer:
    dataset:
        filename: data/rb-domains.log
        max-lines: -1
    model-file: bin/basic.dfw3model
    max-length:
        percentile: 0.99
        penalty: 0.1
    hmm:
        hidden-states: 10
    entropy:
        bins: 1000
        scale: log
        window-widths: [
            30,100,300,1000
        ]
