plugin:
    mode: simple
    model-file: /etc/snort/dns-firewall/basic.snort3model
    whitelist:  /etc/snort/dns-firewall/whitelist.snort3model
    blacklist:  /etc/snort/dns-firewall/blacklist.snort3model
    length:
        min-length: 8
        max-length: 40
        max-length-penalty: 0.1
    hmm:
        weight: 10
    entropy:
        weight: 10
    short-reject:
        block-period: 5
        threshold: -2
        repetitions: 1
    long-reject:
        block-period: 60
        threshold: -3
        repetitions: 5
    permanent-reject:
        threshold: -4
        repetitions: 10

trainer:
    dataset: data/rb-domains.log
    model-file: bin/model.snort3model
    max-lines: -1
    hmm:
        hidden-states: 10
    entropy:
        bins: 1000
        scale: log
        window-widths: [
            30,100,300,1000
        ]
