gini: gini.cc
		g++ -std=c++11 -Wall -O3 gini.cc -o snort4gini

gini-clang: gini.cc
		clang++ -Wall -O3 gini.cc -o snort4gini

markov: markov.cc
		g++ -std=c++11 -Wall -O3 markov.cc -o snort4markov

markov-clang:
		clang++ -Wall -O3 markov.cc -o snort4markov
